# Generated by Django 2.1 on 2020-02-17 06:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0007_auto_20200217_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensescategory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='expensescategory',
            unique_together={('title', 'user')},
        ),
    ]
