# Generated by Django 2.1 on 2020-02-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
