# Generated by Django 2.1 on 2020-02-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_auto_20200215_1716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together={('title', 'id')},
        ),
    ]
